/// Flutter icons DropperIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DropperIcon
///      fonts:
///       - asset: fonts/DropperIcon.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class DropperIcon {
  DropperIcon._();

  static const _kFontFam = 'DropperIcon';

  static const IconData eyedropper =
      const IconData(0xf1fb, fontFamily: _kFontFam);
}
